### ISSUE TITLE
Criar estrutura básica do projeto 

### ISSUE THREAD

**Issue by huogerac** [huogerac/trot-geo-tracking#1]
**Tarefa:**
- Criar uma estrutura básica de projeto Vue 3 + Vite, 
- Usar os componentes do [Vuetify 3](https://next.vuetifyjs.com/en/), assim focamos nas regras de negócio e não em ficar fazendo CSS (depois da fase 2 ou 3 podemos focar em deixar o app bonitão.
- Utilizar node 16 (criar arquivo .nvmrc)

**Comment by HenriqueCCdA** [comment]
Como ficaria a estrutura do repositório com `backend`? 

Teriamos uma pasta `backend` e uma outra `frontend` ?
