### ISSUE TITLE
Mapa de navegação inicial

### ISSUE THREAD

**Issue by huogerac** [huogerac/trot-geo-tracking#6]
Mapa de navegação inicial par dar uma direção das funcionalidades (MVP) da primeira versão

![geotracking-navegação drawio_v0 0 1](https://user-images.githubusercontent.com/962233/212448383-a5e0cd69-df1f-438e-94f2-7d0bbd52e4d6.png)

**Comment by JonathansManoel** [comment]
Interessante seria adicionar tipo de modalidade! 
Caminhada - Corrida - Pedal!
